### ISSUE TITLE
this pod is causing me compile time errors

### ISSUE THREAD

**Issue by stanchiang** [segment-integrations/analytics-ios-integration-crittercism#1]
i have a swift 2.1 app already integrated with the segment pod working properly (tracks events and have other integrations enabled) but adding this pod is throwing the error in the screenshot.

<img width="1097" alt="screen shot 2016-01-27 at 11 41 05 am" src="https://cloud.githubusercontent.com/assets/3621407/12626121/e3a7a9d8-c4eb-11e5-8332-92cfd8680921.png">

**Comment by hankim813** [comment]
@f2prateek @wcjohnson11 any ideas?

**Comment by ladanazita** [comment]
@stanchiang Do you have `use_frameworks!` declared in your podfile?  Removing `use_frameworks!` may do the trick, or manually adding the Crittercism framework to the **Link Binary With Libraries** section of the **Segment-Crittercism** target.

**Comment by ladanazita** [comment]
@stanchiang Haven't heard back here, closing out for now, but let us know if anything comes up!
