### ISSUE TITLE
Wrong class type for factory instance?

### ISSUE THREAD

**Issue by ynnadrules** [segment-integrations/analytics-ios-integration-crittercism#2]
In the factory [implementation's](https://github.com/segment-integrations/analytics-ios-integration-crittercism/blob/master/Pod/Classes/SEGCrittercismIntegrationFactory.m#L10) `+instance` class method shouldn't the `sharedInstance` type be `SEGCrittercismIntegrationFactory` instead of `SEGCrittercismIntegration`?

``` objc
+ (id)instance
{
    static dispatch_once_t once;
    static SEGCrittercismIntegration *sharedInstance; // <-- THIS LINE
    dispatch_once(&once, ^{
        sharedInstance = [[self alloc] init]; // <-- self here is of SEGCrittercismIntegrationFactory
    });
    return sharedInstance;
}
```

 If this is a bug, then it should be checked across all integrations as well because it's not just this integration that does this.

**Comment by f2prateek** [comment]
@ynnadrules Thanks, this indeed looks like a bug! We'll do a full audit for integrations and update them

**Comment by f2prateek** [comment]
I'm a bit surprised the compiler didn't catch this.

**Comment by ynnadrules** [comment]
yeah me too. np!

**Comment by f2prateek** [comment]
Fixed https://github.com/segment-integrations/analytics-ios-integration-crittercism/commit/fc1d15aafa36e5c332db877e97a05593386e15f8
